### PR TITLE
Updated to nUnit 3

### PR DESCRIPTION
**Pull request by TomBeckett**
Update vb-syntax example to NUnit 3.2

### CODE REVIEW

**Comment by CharliePoole** [comment]
@TomBeckett
This looks good to me, although I have only reviewed and not executed it. It needs a second review by a committer before we merge.

Thanks for your work!

**Comment by TomBeckett** [comment]
Wow thank you Charlie ! Its my first submission so really pleased :+1:

**Comment by CharliePoole** [comment]
As you might expect, most of the contributors are C# folks. It's good to add those who use other languages.

It's nice to see that the attributes in VB no longer need to be on the same logical line. The [Is] construction is interesting as well. Perhaps we should add a comment saying what versions of VB are needed to build the sample.

**Comment by CharliePoole** [comment]
This fixes nunit/nunit#232

**Comment by CharliePoole** [comment]
@TomBeckett I just noticed that you only updated one sample. Was that your intention? Any progress is OK, of course!

**Comment by TomBeckett** [comment]
@CharliePoole I took a look at the other sample (within Money) but couldn't see any particular code that needed to be updated? 

Please let me know if I missed something really obvious! I'll be sure to update no problem at all.

**Comment by CharliePoole** [comment]
In that case, let's finish up this one first.

**Comment by rprouse** [comment]
Looks good to me, but doesn't the project file need to be updated to reference NUnit 3 instead of 2.x? I assume that this is pulling the framework from the install. Should we change it to use NuGet?

**Comment by CharliePoole** [comment]
Good point... this sample, and maybe others, goes back to when we used to tell people "Change the reference to match where NUnit is on your own system." Using a package now that we have them makes sense.

**Comment by TomBeckett** [comment]
The framework within the project is also using .NET 2.0. Should this be updated? Perhaps to 4.5.1 or 4.6?

Also, would it be worth adding both projects into a single solution file (i.e. both Syntax and Money within a VB Solution?)

Let me know your thoughts and I can add any changes to this PR :)

**Comment by rprouse** [comment]
Adding the projects to a single solution file is a good idea. I think we did the same thing with the C# samples. As for updating to 4.5.1, let's not do that until we start demonstrating features that need a newer framework. By keeping the version low, the projects can be opened in older versions of VS. That said, back to 2010 is probably fine which is 4.0 right?

**Comment by TomBeckett** [comment]
I've taken a second look at the C Sharp sample project it also includes another project : ExpectedExceptionExample. Would you like this converted into VB? 

It also looks like the C Sharp is not currently a single solution with three projects unless I am reading incorrectly (always possible)

**Comment by CharliePoole** [comment]
Previously we had all the projects for a language in a single solution. I separated them because I felt that folks would generally want to use one project at a time. Also, not having a single solution simplifies maintenance if we get more projects contributed, as each one can stand on its own. It makes our sample repos into a sort of gallery - and might even be front-ended that way eventually.

**Comment by CharliePoole** [comment]
@TomBeckett I wouldn't want to replicate the ExpectedExceptionExample since it shows how to create a DIY version of a feature we would rather not have.

It would be great to eventually have some other example of a framework extension, written in VB.

**Comment by CharliePoole** [comment]
So, summing up, what we need to finish this up is...
1. Decide on a target framework... I'm OK with 2.0 or 4.0.
2. Remove the ref to nunit.framework and use the NUnit package.

Anything else @rprouse ?

@TomBeckett You'll find we often push for keeping each PR restricted in scope. Love to see you do others, however. :-)

**Comment by rprouse** [comment]
@TomBeckett let's leave everything as it currently is except please switch it to using NuGet. There isn't a compelling reason to update the framework yet.

**Comment by TomBeckett** [comment]
Done. Updated the PR to use NuGet package.

**Comment by CharliePoole** [comment]
It looks like you added the package content to the repository. We don't generally do that. Just set up the solution to restore automatically.

**Comment by rprouse** [comment]
Looks good except you ended up checking in the two package directories with all of the binaries. To prevent this, you can add a .gitignore to the root of the repo with one line `packages`.

Can you delete those files from your branch?

**Comment by TomBeckett** [comment]
Updated the PR and removed the packages. Sorry those got included, my GitHub inexperience showing through unfortunately. 

Many thanks for all the patience, hope its correct this time.

**Comment by CharliePoole** [comment]
Looks good to me now.

**Comment by CharliePoole** [comment]
Wait! I don't see that .gitignore file. :-) Sorry 'bout that.

**Comment by rprouse** [comment]
Looks good to me too. We've been going back and forth on this awhile. I will add a .gitignore file rather than do another round.

**Pull request merged**
