### PR TITLE
Removed AssertionHelper from samples

### LINKED ISSUE #7: Remove use of AssertionHelper from samples

### PR DESCRIPTION
**Pull request by TomBeckett**
This fixes #7

### CODE REVIEW

**Comment by CharliePoole** [comment]
@TomBeckett Thanks for doing this. 

It looks good except that you have not removed `Inherits AssertionHelper`. Once that's gone, if it still compiles, you'll know you got everything.

**Comment by ChrisMaddock** [comment]
Charlie, you beat me too it! 😄 There's also the comment at the top of the file that will need updating:

> Each test performs the same operations using the classic syntax (if available) and the new syntax in both the syntax (if available) and the new syntax in both the helper-based and inherited forms.

This PR is removing the 'inherited' form.

Otherwise looks good to me. Thanks!

**Comment by ChrisMaddock** [comment]
We just need to be careful when merging this. @TomBeckett, I think you've got https://github.com/nunit/nunit/issues/7 mixed up with #7 - the latter will close the correct issue, the former will close an unrelated issue in the main framework repo.

I edited your initial post in this PR, but I can see you've also written "fixes nunit/nunit#7" in commit "f49035a", which I can't edit. If you can go back and edit the commit message, that would be great - otherwise we can just reopen nunit/nunit#7 when it gets autoclosed when we merge. 🙂

**Comment by rprouse** [comment]
I've merged and reopened the issue.

**Pull request merged**
